### PR TITLE
Base64 encoded image handling with ViewModel

### PR DESCRIPTION
**Pull request by ktzsolt**
I completed the #44 PR, it is working now on this PR. I couldn't test it with .NET Framework project only .NET 6 so please try it with .NET Framework.

Related issue is https://github.com/egonl/SharpDocx/issues/30

### CODE REVIEW

**Comment by ktzsolt** [comment]
fixed merge conflict with Samples\Documents\Tutorial.docx

**Comment by ktzsolt** [comment]
@egonl Hi! Should I improve something on this to be accepted?

**Comment by egonl** [comment]
Thanks, it's looking good! I still have to test it a bit which will probably be next week.

**Comment by egonl** [comment]
I've done it slightly more generic and added ImageFromBase64, ImageFromUrl and ImageFromStream. See the 2.4-beta branch. Does that work for you?

**Comment by ktzsolt** [comment]
I will check on weekend!

**Comment by ktzsolt** [comment]
> I've done it slightly more generic and added ImageFromBase64, ImageFromUrl and ImageFromStream. See the 2.4-beta branch. Does that work for you?

I reviewed the code on the https://github.com/egonl/SharpDocx/commit/11ed285fc453ee9c232526409f2162b5824c9ef8 commit comparing to master https://github.com/egonl/SharpDocx/commit/95996e21aa55c6e1c3a9bad182aabbb421980ba5 commit and tried out with the sample tutorial (on .net 6), looks good to me!

I close this PR because this is obsolete now, thanks!

**Comment by ktzsolt** [comment]
Hi @egonl !

Any news on merging the 2.4-beta to master and release it?

Thanks!

**Comment by egonl** [comment]
Thanks for the reminder, just released 2.4.0. Enjoy!

**Pull request closed without merging**
