### PR TITLE
Add metafile support, fix image scaling and insert bugs

### PR DESCRIPTION
**Pull request by stephanscheidl**
Dear egonl,

please review my changes and if possible pull them in the official repository.

Best regards,
Stephan

### CODE REVIEW

**Comment by egonl** [comment]
Thanks for the PR. I won't merge it, since there are a couple of issues with it:
- It's using System.Drawing and that's not supported on every platform (see https://learn.microsoft.com/en-us/dotnet/api/system.drawing.imaging?view=dotnet-plat-ext-6.0#remarks).
- Duplicate DocProperties.Ids can also be introduced by other methods, like repeating text blocks.
- I thought the image scaling was already fixed - wasn't it?

However, I've created a v2.3-beta branch (see https://github.com/egonl/SharpDocx/tree/v2.3-beta) which supports EMF-files and de-duplicates DocProperties.Ids. Could you give that a try and let me know if it works ok for you?

Kind regards, Egon.

**Comment by stephanscheidl** [comment]
Dear Egon,

thank you for providing an even better solution to my issues. I am currently testing your implementations and it looks very promising. Everything seems to work like a charm. I hope you are going to consider your improvements for the next official release.

Best regards, Stephan

**Comment by stephanscheidl** [comment]
Thank you Egon for implementing my requested features. Please keep up your excellent work. It is highly appreciated. BR, Stephan

**Comment by egonl** [comment]
Just released v2.3.0.

**Pull request closed without merging**
