### PR TITLE
Split File & Stream usage

### PR DESCRIPTION
**Pull request by alphamax**
Keep DocumentBase but put on top DocumentFileBase and DocumentStreamBase.
Adapt tests to generate also "Stream Version"

### CODE REVIEW

**Comment by alphamax** [comment]
Feel free to comment if I made any mistake :)
I will fix

**Comment by egonl** [comment]
Thank you! I'll have to test it a little bit and I'll let you know if I find anything.

**Comment by vpellichero** [comment]
Is it possible to merge this PR ? I'm very interested by the Stream support.

**Comment by alphamax** [comment]
Using it for few weeks and seems to work :D

**Comment by btoepferDm** [comment]
@egonl how long will it take until this will be released as a package?
Me and my Team really want this feature and would like to avoid forking the Repo.

**Comment by egonl** [comment]
I'm a bit reluctant, because accepting a random stream containing code that will be executed is a huge security risk. What is your exact use case for which you need streams?

**Comment by btoepferDm** [comment]
Any news, thoughts or insights on this Topic?

**Comment by egonl** [comment]
@btoepferDm Addes support for view streams in #69. Could you give that a try?

**Comment by btoepferDm** [comment]
> @btoepferDm Added support for view streams in #69. Could you give that a try?

Thank you very much, i will give it a try, hopefully today, latest tomorrow. 
Will get back to you with feedback, as soon as i have :)

**Comment by egonl** [comment]
Implemented in #69, closing PR.

**Pull request closed without merging**
